# -*- coding: utf-8 -*-
"""Data_Augmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rYNmyqONOln7gk8CJ9e8h_kJlffTKwGK
"""

from google.colab import drive
drive.mount('/content/drive')

!unzip -q /content/drive/MyDrive/train_images.zip -d /content/

import os

if os.path.exists('/content/train_images'):
    !rm -rf /content/train_images
    print("Removed existing /content/train_images directory.")

!unzip -q /content/drive/MyDrive/train_images.zip -d /content/
print("Unzipped train_images.zip to /content/")

# verifying contents of directory
print("Contents of /content/train_images/ (first 5 items):")
!ls -F /content/train_images/ | head -n 5

!cp /content/drive/MyDrive/train.csv /content/

import pandas as pd
from PIL import Image
import torch
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as transforms

class ButterflyDataset(Dataset):
    def __init__(self, csv_file, img_dir, transform=None):
        self.img_labels = pd.read_csv(csv_file)
        self.img_dir = img_dir
        self.transform = transform

        # map species name to id numbers
        self.classes = sorted(self.img_labels['TARGET'].unique())
        self.class_to_idx = {cls_name: i for i, cls_name in enumerate(self.classes)}

    def __len__(self):
        return len(self.img_labels)

    def __getitem__(self, idx):
        img_name = self.img_labels.loc[idx, 'file_name']
        img_path = os.path.join(self.img_dir, img_name)
        image = Image.open(img_path).convert("RGB")

        string_label = self.img_labels.loc[idx, 'TARGET']
        numeric_label = self.class_to_idx[string_label]

        if self.transform:
            image = self.transform(image)
        return image, numeric_label

''' TUTORIAL: HOW TO USE THIS IN MODELS '''

# 1. Define the data augmentation


# 2. Load the CSV and Images
# (Make sure 'train.csv' and the 'train_images' folder are in the same folder as this code)
train_transforms = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(p=0.5), # 50% chance to flip
    transforms.RandomRotation(degrees=15),  # Rotate up to 15 degrees
    transforms.ColorJitter(brightness=0.2, contrast=0.2), # Random lighting
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])


my_dataset = ButterflyDataset(csv_file='/content/train.csv',
                              img_dir='/content/train_images',
                              transform=train_transforms)

# 3. Create the DataLoader to pass to CNN
train_loader = DataLoader(my_dataset, batch_size=32, shuffle=True)
print(f"Dataset loaded! Total images found: {len(my_dataset)}")

'''Trial Run'''

import matplotlib.pyplot as plt
import numpy as np

# Helper function to show an image
def imshow(img):
    img = img / 2 + 0.5     # unnormalizing
    npimg = img.numpy()
    plt.imshow(np.transpose(npimg, (1, 2, 0)))
    plt.show()


my_dataset = ButterflyDataset(csv_file='/content/train.csv',
                              img_dir='/content/train_images/train_images',
                              transform=train_transforms)
train_loader = DataLoader(my_dataset, batch_size=32, shuffle=True)

# get one batch of items and shwo the first image to test augmentation
dataiter = iter(train_loader)
images, labels = next(dataiter)
print(f"Showing species index: {labels[0]}")
imshow(images[0])

# Load your training labels
df = pd.read_csv('/content/train.csv')

# Count how many images are in each class
class_counts = df['TARGET'].value_counts()

# Print the three numbers you need for the report:
print(f"Most frequent class (Max images): {class_counts.max()}")
print(f"Least frequent class (Min images): {class_counts.min()}")
print(f"Average images per class: {class_counts.mean():.1f}")

'''Data Splitting'''
# Show the exact numbers of your split
train_size = int(0.8 * len(my_dataset))
val_size = len(my_dataset) - train_size
print(f"We split the data into {train_size} training images and {val_size} validation images (80/20 split).")

'''Quantitative Comparison of Class Balance'''


df = pd.read_csv('/content/train.csv')
def categorize(name):
    name = name.upper()
    if 'MOTH' in name:
        return 'Moth'
    else:
        return 'Butterfly' # Most targets in this dataset are butterflies unless labeled MOTH

df['Category'] = df['TARGET'].apply(categorize)

# ge
counts = df['TARGET'].value_counts()
print("--- TOP 5 SPECIES (Most Images) ---")
print(counts.head(5))
print("\n--- BOTTOM 5 SPECIES (Least Images) ---")
print(counts.tail(5))

# 3. Get the Butterfly vs Moth breakdown
category_counts = df['Category'].value_counts()
print("\n--- DATASET BREAKDOWN ---")
print(category_counts)

# Plotting the Category split
df['Category'].value_counts().plot(kind='pie', autopct='%1.1f%%', colors=['skyblue', 'lightcoral'])
plt.title('Percentage of Butterflies vs. Moths')
plt.ylabel('')
plt.show()